on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lints:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: git checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - name: Validate Action
        run: nix develop -c action-validator -v ./.github/workflows/workflow.yml
      - name: Check syntax
        run: nix develop -c prettier --check .
      - name: Check GitHub Actions security compliance
        run: nix develop -c zizmor .github

  DeterminateCI:
    uses: ./.github/workflows/workflow.yml
    permissions:
      id-token: write
      contents: read
    with:
      directory: ./tests/smoke
